### ISSUE TITLE
电音小沙子

### ISSUE THREAD

**Issue by Pantyhose-X** [2439905184/minetest_dev_wiki_zh_cn_mirrow#2]
[Godot的体素工具](https://github.com/Zylann/godot_voxel)
[Gradle 构建工具](https://github.com/gradle/gradle)
https://nvlabs.github.io/GANcraft/
https://nvlabs.github.io/SPADE/

网状网络 作为游戏服务器，每个人都可以创建自己的服务器节点，所有人都可以链接
WebRTC p2p
https://github.com/yggdrasil-network/yggdrasil-go
https://github.com/slackhq/nebula
https://github.com/dswd/vpncloud

区域块 网络
https://lokinet.org/
https://enjin.io/software/enjincraft#join
https://cosmos.network/
https://ethereum.org/
https://matrix.org/

Godot区域块
https://godotengine.org/asset-library/asset/607
https://github.com/enjin/enjin-godot-sdk

去中心化世界的基础设施
https://github.com/dappnode

**Comment by 2439905184** [comment]
这个wiki镜像是我用开源软件httrack做的，只是为了方便写mod，官网的wiki有点慢。我事情比较多，没空做minetest视频教程。你自己用谷歌翻译看那个网站，自己学。

**Comment by 2439905184** [comment]
Download the tarball from here: https://github.com/minetest-tools/mcimp ... master.zip
    Extract it
    Launch the converter
···
wget https://github.com/sofar/mcimport/archive/master.zip
unzip master.zip
mcimport-master/mcimport.sh
···

**Comment by 2439905184** [comment]
迄今为止
    开发者
    帖子：2132
    加入时间：2015年1月16日星期五
    GitHub：sofer
    IRC：沙发
    游戏中：沙发

将Minecraft地图转换为Minetest世界

发布者：»»十二月12，2015 00:31发表
mcimport项目为整个Minecraft地图（Minecraft保存）提供了一个世界转换器，输出是一个新的，可玩的Minetest世界。

该项目开始时是由Nore和dgm555编写的基本python转换。从那时起，我已经更新了该项目，并花了很多时间使转换越来越完整。我们也将这两个项目合并到了minetest-tools组织中。

转换是需要Python的单步过程。转换完成后，您的世界就可以玩了！对于大世界，即使您的世界很大，此过程也可能需要数小时，甚至数天。

GitHub：https：//github.com/minetest-tools/mcimport
下载：https://github.com/minetest-tools/mcimp ... master.zip
平台：Linux（其他可能会用，但需要额外的软件）
执照：X11

用法：

    从这里下载压缩包：https://github.com/minetest-tools/mcimp ... master.zip
    提取它
    启动转换器

或者，要列出确切的终端命令，请将以下文本剪切并粘贴到终端中：

代码：全选

wget https://github.com/sofar/mcimport/archive/master.zip
解压master.zip
mcimport-master / mcimport.sh

Minecraft测试模式：

图像

转换结果：

图像



不过，我的工作方式有所不同-我的重点不是“精确复制”，而是创建一个可玩的MC世界的近似游戏。

因此，我希望诸如门，床，熔炉之类的东西能够正常工作，并且砌块是有用且可用的。但是无目的或在我的测试中不存在的方块将被删除或替换为在MT游戏中有意义的等价物。块的旋转已仔细完成并得到验证。

-翡翠矿石转化为石头
-红石可以通过工作压力板，电线，笔记本，按钮，控制杆和更多其他东西转换为远景

转换MC存档游戏或世界时，它的格式应为MC 1.11。我不支持旧格式。该代码还编写了一些额外的文件，以使它们在mapgen中都能正常运行，主要是修复了水位并使您可以轻松地将mapgen调整为单个节点。注意：现在，地图可以正确地离开MC的北，而离开MT的北（有效地更改每个块的坐标）。

Mods：需要大量的mods-并不奇怪，不太钝或很难找到mods，这些都是大多数服务器拥有的非常常见的mods，其中大多数都包含在biomes_lib，plantlife，mesecons，moretree，moreblocks，nether，flowerpot和下位的mod已经（以及其他一些）。存在一个脚本来帮助您下载所有需要的mod。

转换器将在world文件夹中创建所有必需的配置文件，并且该世界应该可以在没有任何额外配置的情况下进行播放。但是，您可能希望在首次在minetest游戏中加载世界之前调整mapgen参数。当前，所有mapgen将被禁用，以防止mapgen覆盖世界内容。

要下载所有必需的mod，需要在world文件夹中编写一个名为get-mods.sh的脚本。运行此脚本将自动为您的转换世界获取正确的mod及其最新版本。

**Comment by 2439905184** [comment]
我在研究开源游戏引擎怎么接入国内的安卓广告sdk，自己做游戏，靠广告赚一点收入，又没有版号，只能免费游戏，上steam没钱，缺钱

**Comment by 2439905184** [comment]
我整了一个简单的web 视觉小说框架 开源 。要看吗，在https://github.com/little-game-and-simple-software/EasyAvgFrameWork

**Comment by Pantyhose-X** [comment]
> 我整了一个简单的web 视觉小说框架 开源 。要看吗，在https://github.com/little-game-and-simple-software/EasyAvgFrameWork

我看过你的视频·视觉小说 只是很浪费时间，所以我不会用

**Comment by 2439905184** [comment]
是的，处于技术研究做的，要做游戏，建议使用其他的工具。
另外，我还没有完整的整理一遍这个工具的设计逻辑（做视频），所以我知道怎么用，别人不一定知道

**Comment by Pantyhose-X** [comment]
我有一个好想法 你可以开发一个 监听输入法工具，应用于学习语言，这样可以纠正发音和加深记忆，调用文本转语音TTS 朗读输入单词或句子。 `输入空格` 后TTS朗读单词，`输入空格`10秒后朗读句子。
你可以内置 [mozilla文字转语音](https://github.com/mozilla/TTS) 或调用Win10内置的或调用Win10安装的
>
`视频例子`https://www.youtube.com/watch?v=YPBn6D6pf78&feature=youtu.be&t=213
>
Android或 iOS 你可以做成输入法，你可以基于[OpenBoard](https://github.com/dslul/openboard)或[Simple Keyboard](https://github.com/rkkr/simple-keyboard)、内置mozilla文字转语音或调用google文本转语音TTS。
>
不以英语为母语的人都需要学习英语，市场非常广

**Comment by Pantyhose-X** [comment]
Minetest中文论坛：https://minetest.cosoc.cn

**Comment by Pantyhose-X** [comment]
开源游戏引擎接入区域块或以太坊、对于可以创建服务器的游戏，每个人都可以创建自己的服务器，所有人都可以链接节点
https://cosmos.network/
https://ethereum.org/
https://matrix.org/

**Comment by 2439905184** [comment]
棒。Godot可以用吗

**Comment by Pantyhose-X** [comment]
> 棒。Godot可以用吗

可以
https://godotengine.org/asset-library/asset/607
https://github.com/enjin/enjin-godot-sdk

**Comment by Pantyhose-X** [comment]
> [Godot的体素工具](https://github.com/Zylann/godot_voxel)
> [Gradle 构建工具](https://github.com/gradle/gradle)

@2439905184

**Comment by 2439905184** [comment]
谢谢

**Comment by 2439905184** [comment]
@Pantyhose-X 我想问一下，minetest的服务器装了mod，客户端自动同步mod数据是怎么实现的，下载在内存里吗？

**Comment by Pantyhose-X** [comment]
> @Pantyhose-X 我想问一下，minetest的服务器装了mod，客户端自动同步mod数据是怎么实现的，下载在内存里吗？

不清楚你可以去 Minetest中文论坛：https://minetest.cosoc.cn  或官方Discord https://discord.gg/minetest 问问

**Comment by Pantyhose-X** [comment]
从文本中AI 生成图像 https://openai.com/blog/dall-e/
